{{- if (.Values.installNamespace) -}}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    linkerd.io/extension: buoyant
{{ end -}}
