# This file specifies which linters golangci-lint should run.
#
# For descriptions of all available linters, run:
# ./target/bin/.golangci-lint-1.42.0 linters
# or browse to:
# https://github.com/golangci/golangci-lint#supported-linters

run:
  deadline: 5m
issues:
  exclude-use-default: false
linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - errname
  - exportloopref
  - goconst
  - goheader
  - goimports
  - gomodguard
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - nolintlint
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  # TODO: enable more linters!
  # - dupl
  # - exhaustive
  # - funlen
  # - gci
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  # - gocritic
  # - gocyclo
  # - godot
  # - godox
  # - goerr113
  # - gofmt
  # - gofumpt
  # - golint
  # - gomnd
  # - gosec
  # - lll
  # - nestif
  # - nlreturn
  # - noctx
  # - prealloc
  # - stylecheck
  # - testpackage
  # - wsl
  disable:
  - errcheck
  - staticcheck
