#
# Buoyant Cloud Agent
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buoyant-cloud-agent
  {{- if eq .Release.Service "Buoyant Cloud" }}
  namespace: {{.Release.Namespace}}
  {{- end }}
  annotations:
    buoyant.cloud/is-agent: "true"
    buoyant.cloud/version: v{{ .Chart.Version }}
    buoyant.cloud/service-name: agent
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/version: v{{ .Chart.Version }}
    app.kubernetes.io/part-of: buoyant-cloud
    linkerd.io/extension: buoyant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buoyant-cloud-agent
  template:
    metadata:
      labels:
        app: buoyant-cloud-agent
      annotations:
        config.linkerd.io/skip-outbound-ports: "4191"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccount: buoyant-cloud-agent
      containers:
      - name: buoyant-cloud-agent
        image: {{ .Values.agent.image }}:{{ default (printf "v%s" .Chart.Version) .Values.agent.imageVersion }}
        args:
        - "agent"
        - "-grpc-addr={{ .Values.agent.apiAddress }}"
        - "-log-level={{ .Values.agent.logLevel }}"
        - "-api-addr={{ .Values.api.apiAddress }}"
        - "-agent-id=$(AGENT_ID)"
        {{- if .Values.agent.noTLS }}
        - "-no-tls"
        {{- end }}
        env:
        - name: BUOYANT_CLOUD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: buoyant-cloud-org-credentials
        - name: BUOYANT_CLOUD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: buoyant-cloud-org-credentials
        - name: AGENT_ID
          valueFrom:
            configMapKeyRef:
              key: agent_id
              name: agent-metadata
        ports:
        - name: admin
          containerPort: 9990
        livenessProbe:
          httpGet:
            path: /ping
            port: 9990
        readinessProbe:
          httpGet:
            path: /ready
            port: 9990
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: "2"
            memory: 5000Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      initContainers:
      - name: buoyant-cloud-agent-registrator
        image: {{ .Values.agent.image }}:{{ default (printf "v%s" .Chart.Version) .Values.agent.imageVersion }}
        args:
        - "registrator"
        - "-log-level={{ .Values.agent.logLevel }}"
        - "-api-addr={{ .Values.api.apiAddress }}"
        {{- if .Values.agent.noTLS }}
        - "-no-tls"
        {{- end }}
        env:
        - name: BUOYANT_CLOUD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: buoyant-cloud-org-credentials
        - name: BUOYANT_CLOUD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: buoyant-cloud-org-credentials
