{{- if eq .Release.Service "Buoyant Cloud" -}}
#
# Buoyant Cloud Namespace
#
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
    linkerd.io/extension: buoyant
{{ end -}}
