kind: ServiceAccount
apiVersion: v1
metadata:
  name: buoyant-cloud-agent
  {{- if eq .Release.Service "Buoyant Cloud" }}
  namespace: {{.Release.Namespace}}
  {{- end }}
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buoyant-cloud-agent
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
rules:
- apiGroups: [""]
  resources: ["services", "pods", "events", "nodes", "nodes/proxy", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy.linkerd.io"]
  resources: ["servers", "serverauthorizations"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["linkerd.io"]
  resources: ["serviceprofiles"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["split.smi-spec.io"]
  resources: ["trafficsplits"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["multicluster.linkerd.io"]
  resources: ["links"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["linkerd-config", "linkerd-identity-trust-roots"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buoyant-cloud-agent
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buoyant-cloud-agent
subjects:
- kind: ServiceAccount
  name: buoyant-cloud-agent
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.Namespace}}
  name: buoyant-cloud-agent
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["agent-metadata"]
  verbs: ["get", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{.Release.Namespace}}
  name: buoyant-cloud-agent
  labels:
    app.kubernetes.io/part-of: buoyant-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buoyant-cloud-agent
subjects:
- kind: ServiceAccount
  name: buoyant-cloud-agent
  namespace: {{.Release.Namespace}}
