metadata:
  agentID: fake-agent-id
  agentName: fake-agent-name
api:
  apiAddress: dockerhost:8082
  noTLS: true
  clientID: fake-client-id
  clientSecret: fake-client-secret
agent:
  apiAddress: dockerhost:8086
  noTLS: true
  imageVersion: ci-run
  logLevel: debug
metrics:
  apiAddress: dockerhost:8087
  noTLS: true
  logLevel: debug
