agent:
  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443

  # -- imageVersion of the buoyant-cloud-agent pod
  imageVersion:

  # -- Disable TLS. Only use for testing.
  insecure: false

  # -- Log level for the buoyant-cloud-agent pod
  logLevel: info

metrics:
  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443

  # -- Disable TLS. Only use for testing.
  insecure: false

  # -- Log level for the buoyant-cloud-metrics pod
  logLevel: info

metadata:
  # -- The ID for this agent
  agentID:

  # -- The name for this agent. Required.
  agentName:

api:
  # -- The client id. Required.
  clientID:

  # -- The client secret. Required.
  clientSecret:

  # -- API address for Buoyant Cloud
  apiAddress: api.buoyant.cloud:443
