kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dataplane-upgrade
  labels:
    app.kubernetes.io/part-of: buoyant-operator
    app.kubernetes.io/component: dataplane-upgrade
    helm.sh/chart: {{.Chart.Name}}-{{printf "v%s" .Chart.Version}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dataplane-upgrade
subjects:
- kind: ServiceAccount
  name: dataplane-upgrade
  namespace: {{.Release.Namespace}}
