name: Unit tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  go_unit_tests:
    runs-on: ubuntu-18.04
    container:
      image: golang:1.15.8
    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: go test -race -v ./...
